controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
achat_tshirt:
    path: /cart/achat
    controller: App\Controller\CartController::achatTshirt
    methods: [GET, POST]